repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-json
        exclude: ^(ui|notebooks|tests)/
      - id: pretty-format-json
        exclude: ^(ui|notebooks|tests)/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args:
          - --fix
        exclude: ^(ui)/
      - id: ruff-format
        exclude: ^(ui)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        exclude: ^(docs|tests|ui)/
