/*-------------------------------------
Copyright: CEA-LIST/DIASI/SIALV/LVA
Author : pixano@cea.fr
License: CECILL-C
-------------------------------------*/

// Imports
import type { Meta, StoryObj } from "@storybook/svelte";

import { Histogram } from "@pixano/core";

const meta = {
  title: "Pixano/Components/UI/Histogram",
  component: Histogram,
  tags: ["autodocs"],
} satisfies Meta<Histogram>;

export default meta;
type Story = StoryObj<typeof meta>;

export const CategoricalFewValues: Story = {
  args: {
    hist: {
      name: "Is Group Of",
      type: "categorical",
      histogram: [
        { "Is Group Of": "false", counts: 838421, split: "train" },
        { "Is Group Of": "true", counts: 9901, split: "train" },
        { "Is Group Of": "false", counts: 29986, split: "val" },
        { "Is Group Of": "true", counts: 376, split: "val" },
      ],
    },
  },
};

export const CategoricalManyValues: Story = {
  args: {
    hist: {
      name: "Category",
      type: "categorical",
      histogram: [
        { Category: "person", counts: 258881, split: "train" },
        { Category: "car", counts: 43321, split: "train" },
        { Category: "chair", counts: 37951, split: "train" },
        { Category: "book", counts: 24376, split: "train" },
        { Category: "bottle", counts: 24041, split: "train" },
        { Category: "cup", counts: 20368, split: "train" },
        { Category: "dining table", counts: 15479, split: "train" },
        { Category: "bowl", counts: 14154, split: "train" },
        { Category: "traffic light", counts: 12670, split: "train" },
        { Category: "handbag", counts: 12175, split: "train" },
        { Category: "umbrella", counts: 11236, split: "train" },
        { Category: "bird", counts: 10679, split: "train" },
        { Category: "boat", counts: 10631, split: "train" },
        { Category: "truck", counts: 9864, split: "train" },
        { Category: "bench", counts: 9683, split: "train" },
        { Category: "sheep", counts: 9352, split: "train" },
        { Category: "banana", counts: 9340, split: "train" },
        { Category: "kite", counts: 8938, split: "train" },
        { Category: "motorcycle", counts: 8591, split: "train" },
        { Category: "backpack", counts: 8570, split: "train" },
        { Category: "potted plant", counts: 8535, split: "train" },
        { Category: "cow", counts: 8007, split: "train" },
        { Category: "wine glass", counts: 7812, split: "train" },
        { Category: "carrot", counts: 7764, split: "train" },
        { Category: "knife", counts: 7661, split: "train" },
        { Category: "broccoli", counts: 7215, split: "train" },
        { Category: "donut", counts: 7050, split: "train" },
        { Category: "bicycle", counts: 6999, split: "train" },
        { Category: "skis", counts: 6553, split: "train" },
        { Category: "vase", counts: 6531, split: "train" },
        { Category: "horse", counts: 6475, split: "train" },
        { Category: "tie", counts: 6435, split: "train" },
        { Category: "cell phone", counts: 6350, split: "train" },
        { Category: "cake", counts: 6285, split: "train" },
        { Category: "sports ball", counts: 6273, split: "train" },
        { Category: "orange", counts: 6270, split: "train" },
        { Category: "clock", counts: 6254, split: "train" },
        { Category: "suitcase", counts: 6098, split: "train" },
        { Category: "spoon", counts: 6095, split: "train" },
        { Category: "surfboard", counts: 6064, split: "train" },
        { Category: "bus", counts: 5993, split: "train" },
        { Category: "apple", counts: 5772, split: "train" },
        { Category: "pizza", counts: 5764, split: "train" },
        { Category: "tv", counts: 5716, split: "train" },
        { Category: "couch", counts: 5678, split: "train" },
        { Category: "remote", counts: 5656, split: "train" },
        { Category: "sink", counts: 5526, split: "train" },
        { Category: "skateboard", counts: 5478, split: "train" },
        { Category: "dog", counts: 5454, split: "train" },
        { Category: "elephant", counts: 5448, split: "train" },
        { Category: "fork", counts: 5390, split: "train" },
        { Category: "zebra", counts: 5261, split: "train" },
        { Category: "airplane", counts: 5065, split: "train" },
        { Category: "giraffe", counts: 5055, split: "train" },
        { Category: "laptop", counts: 4901, split: "train" },
        { Category: "tennis racket", counts: 4755, split: "train" },
        { Category: "teddy bear", counts: 4737, split: "train" },
        { Category: "cat", counts: 4691, split: "train" },
        { Category: "train", counts: 4520, split: "train" },
        { Category: "sandwich", counts: 4304, split: "train" },
        { Category: "bed", counts: 4138, split: "train" },
        { Category: "toilet", counts: 4100, split: "train" },
        { Category: "baseball glove", counts: 3705, split: "train" },
        { Category: "oven", counts: 3296, split: "train" },
        { Category: "baseball bat", counts: 3234, split: "train" },
        { Category: "hot dog", counts: 2882, split: "train" },
        { Category: "keyboard", counts: 2817, split: "train" },
        { Category: "frisbee", counts: 2665, split: "train" },
        { Category: "snowboard", counts: 2657, split: "train" },
        { Category: "refrigerator", counts: 2607, split: "train" },
        { Category: "mouse", counts: 2239, split: "train" },
        { Category: "stop sign", counts: 1949, split: "train" },
        { Category: "toothbrush", counts: 1930, split: "train" },
        { Category: "fire hydrant", counts: 1846, split: "train" },
        { Category: "microwave", counts: 1645, split: "train" },
        { Category: "scissors", counts: 1448, split: "train" },
        { Category: "bear", counts: 1281, split: "train" },
        { Category: "parking meter", counts: 1279, split: "train" },
        { Category: "toaster", counts: 222, split: "train" },
        { Category: "hair drier", counts: 192, split: "train" },
        { Category: "person", counts: 9243, split: "val" },
        { Category: "car", counts: 1582, split: "val" },
        { Category: "chair", counts: 1478, split: "val" },
        { Category: "book", counts: 934, split: "val" },
        { Category: "bottle", counts: 857, split: "val" },
        { Category: "cup", counts: 726, split: "val" },
        { Category: "dining table", counts: 581, split: "val" },
        { Category: "bowl", counts: 508, split: "val" },
        { Category: "traffic light", counts: 504, split: "val" },
        { Category: "handbag", counts: 438, split: "val" },
        { Category: "bench", counts: 363, split: "val" },
        { Category: "bird", counts: 360, split: "val" },
        { Category: "cow", counts: 336, split: "val" },
        { Category: "carrot", counts: 331, split: "val" },
        { Category: "boat", counts: 329, split: "val" },
        { Category: "backpack", counts: 317, split: "val" },
        { Category: "truck", counts: 314, split: "val" },
        { Category: "umbrella", counts: 305, split: "val" },
        { Category: "motorcycle", counts: 288, split: "val" },
        { Category: "sheep", counts: 288, split: "val" },
        { Category: "knife", counts: 287, split: "val" },
        { Category: "wine glass", counts: 284, split: "val" },
        { Category: "donut", counts: 283, split: "val" },
        { Category: "banana", counts: 281, split: "val" },
        { Category: "cake", counts: 278, split: "val" },
        { Category: "potted plant", counts: 278, split: "val" },
        { Category: "kite", counts: 272, split: "val" },
        { Category: "bicycle", counts: 270, split: "val" },
        { Category: "broccoli", counts: 268, split: "val" },
        { Category: "pizza", counts: 256, split: "val" },
        { Category: "suitcase", counts: 246, split: "val" },
        { Category: "bus", counts: 242, split: "val" },
        { Category: "orange", counts: 238, split: "val" },
        { Category: "horse", counts: 238, split: "val" },
        { Category: "tv", counts: 230, split: "val" },
        { Category: "sports ball", counts: 229, split: "val" },
        { Category: "remote", counts: 229, split: "val" },
        { Category: "elephant", counts: 224, split: "val" },
        { Category: "cell phone", counts: 223, split: "val" },
        { Category: "clock", counts: 219, split: "val" },
        { Category: "tie", counts: 214, split: "val" },
        { Category: "vase", counts: 213, split: "val" },
        { Category: "spoon", counts: 212, split: "val" },
        { Category: "surfboard", counts: 205, split: "val" },
        { Category: "couch", counts: 203, split: "val" },
        { Category: "zebra", counts: 200, split: "val" },
        { Category: "tennis racket", counts: 199, split: "val" },
        { Category: "skis", counts: 193, split: "val" },
        { Category: "laptop", counts: 190, split: "val" },
        { Category: "giraffe", counts: 187, split: "val" },
        { Category: "dog", counts: 182, split: "val" },
        { Category: "fork", counts: 180, split: "val" },
        { Category: "sink", counts: 177, split: "val" },
        { Category: "cat", counts: 168, split: "val" },
        { Category: "apple", counts: 164, split: "val" },
        { Category: "sandwich", counts: 162, split: "val" },
        { Category: "teddy bear", counts: 161, split: "val" },
        { Category: "toilet", counts: 151, split: "val" },
        { Category: "train", counts: 147, split: "val" },
        { Category: "skateboard", counts: 138, split: "val" },
        { Category: "bed", counts: 137, split: "val" },
        { Category: "baseball bat", counts: 131, split: "val" },
        { Category: "keyboard", counts: 129, split: "val" },
        { Category: "baseball glove", counts: 115, split: "val" },
        { Category: "oven", counts: 115, split: "val" },
        { Category: "hot dog", counts: 107, split: "val" },
        { Category: "airplane", counts: 105, split: "val" },
        { Category: "refrigerator", counts: 103, split: "val" },
        { Category: "frisbee", counts: 99, split: "val" },
        { Category: "fire hydrant", counts: 86, split: "val" },
        { Category: "mouse", counts: 85, split: "val" },
        { Category: "bear", counts: 61, split: "val" },
        { Category: "stop sign", counts: 61, split: "val" },
        { Category: "snowboard", counts: 51, split: "val" },
        { Category: "parking meter", counts: 51, split: "val" },
        { Category: "microwave", counts: 43, split: "val" },
        { Category: "toothbrush", counts: 33, split: "val" },
        { Category: "scissors", counts: 31, split: "val" },
        { Category: "toaster", counts: 8, split: "val" },
        { Category: "hair drier", counts: 8, split: "val" },
      ],
    },
  },
};

export const Numerical: Story = {
  args: {
    hist: {
      name: "Area (%)",
      type: "numerical",
      range: [0.0, 100.0],
      histogram: [
        { bin_start: 0.0, bin_end: 10.0, counts: 749476, split: "train" },
        { bin_start: 10.0, bin_end: 20.0, counts: 50322, split: "train" },
        { bin_start: 20.0, bin_end: 30.0, counts: 21271, split: "train" },
        { bin_start: 30.0, bin_end: 40.0, counts: 11113, split: "train" },
        { bin_start: 40.0, bin_end: 50.0, counts: 5940, split: "train" },
        { bin_start: 50.0, bin_end: 60.0, counts: 3500, split: "train" },
        { bin_start: 60.0, bin_end: 70.0, counts: 2068, split: "train" },
        { bin_start: 70.0, bin_end: 80.0, counts: 1406, split: "train" },
        { bin_start: 80.0, bin_end: 90.0, counts: 1148, split: "train" },
        { bin_start: 90.0, bin_end: 100.0, counts: 2074, split: "train" },
        { bin_start: 0.0, bin_end: 10.0, counts: 26792, split: "val" },
        { bin_start: 10.0, bin_end: 20.0, counts: 1799, split: "val" },
        { bin_start: 20.0, bin_end: 30.0, counts: 811, split: "val" },
        { bin_start: 30.0, bin_end: 40.0, counts: 377, split: "val" },
        { bin_start: 40.0, bin_end: 50.0, counts: 225, split: "val" },
        { bin_start: 50.0, bin_end: 60.0, counts: 121, split: "val" },
        { bin_start: 60.0, bin_end: 70.0, counts: 74, split: "val" },
        { bin_start: 70.0, bin_end: 80.0, counts: 47, split: "val" },
        { bin_start: 80.0, bin_end: 90.0, counts: 46, split: "val" },
        { bin_start: 90.0, bin_end: 100.0, counts: 70, split: "val" },
      ],
    },
  },
};
