import Konva from "konva";
import simplify from "simplify-js";

import type { PolygonGroupPoint } from "../lib/types/canvas2dTypes";

export const parseSvgPath = (svgPath: string): PolygonGroupPoint[] => {
  const regex = /([ML]?)\s*([\d.]+)\s+([\d.]+)/g;
  let match: RegExpExecArray | null;
  let result: { x: number; y: number }[] = [];
  while ((match = regex.exec(svgPath)) !== null) {
    const [, , x, y] = match;
    result.push({ x: parseFloat(x), y: parseFloat(y) });
  }
  result = simplify(result, 4, true);
  return result.map((r, i) => ({ ...r, id: i }));
};

export const convertPointToSvg = (points: PolygonGroupPoint[]) =>
  points.reduce((acc, val, i) => {
    if (i === 0) {
      return `M${val.x} ${val.y}`;
    }
    if (i === 1) {
      return `${acc} L${val.x} ${val.y}`;
    }
    return `${acc} ${val.x} ${val.y}`;
  }, "");

export const hexToRGBA = (hex: string, alpha: number) => {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r},${g},${b},${alpha})`;
};

//utility functions to extract coords from SVG
//works only with SVG format "Mx0 y0 Lx1 y1 ... xn yn"
// --> format generated by convertSegmentsToSVG
function m_part(svg: string) {
  const splits = svg.split(" ");
  const x = splits[0].slice(1); //remove "M"
  return { x: parseInt(x), y: parseInt(splits[1]) };
}
function l_part(svg: string) {
  const splits = svg.split(" ");
  const x0 = splits[2]?.slice(1); //remove "L"
  const res = [{ x: parseInt(x0), y: parseInt(splits[3]) }];
  for (let i = 4; i < splits.length; i += 2) {
    res.push({
      x: parseInt(splits[i]),
      y: parseInt(splits[i + 1]),
    });
  }
  return res;
}

export const sceneFunc = (ctx: Konva.Context, shape: Konva.Shape, svg: string[]) => {
  ctx.beginPath();
  for (let i = 0; i < svg.length; ++i) {
    const start = m_part(svg[i]);
    ctx.moveTo(start.x, start.y);
    const l_pts = l_part(svg[i]);
    for (const pt of l_pts) {
      ctx.lineTo(pt.x, pt.y);
    }
  }
  ctx.fillStrokeShape(shape);
};
