# =====================================
# Copyright: CEA-LIST/DIASI/SIALV/LVA
# Author : pixano@cea.fr
# License: CECILL-C
# =====================================

from .annotations import (
    Annotation,
    BaseIntrinsics,
    BBox,
    BBox3D,
    CamCalibration,
    CompressedRLE,
    Extrinsics,
    Intrinsics,
    KeyPoints,
    KeyPoints3D,
    Tracklet,
    create_bbox,
    create_bbox3d,
    create_cam_calibration,
    create_compressed_rle,
    create_keypoints,
    create_keypoints3d,
    create_tracklet,
    is_annotation,
    is_bbox,
    is_bbox3d,
    is_cam_calibration,
    is_compressed_rle,
    is_keypoints,
    is_keypoints3d,
    is_tracklet,
)
from .base_schema import BaseSchema, is_base_schema
from .embeddings import (
    Embedding,
    ViewEmbedding,
    create_view_embedding_function,
    is_embedding,
    is_view_embedding,
)
from .entities import (
    Entity,
    Track,
    create_track,
    is_entity,
    is_track,
)
from .items import Item, is_item
from .registry import register_schema
from .schema_group import SchemaGroup
from .views import (
    Image,
    PointCloud,
    SequenceFrame,
    Video,
    View,
    create_image,
    create_point_cloud,
    create_sequence_frame,
    create_video,
    is_image,
    is_point_cloud,
    is_sequence_frame,
    is_video,
    is_view,
)


__all__ = [
    "Annotation",
    "BaseIntrinsics",
    "BaseSchema",
    "BBox",
    "BBox3D",
    "CamCalibration",
    "CompressedRLE",
    "Embedding",
    "Entity",
    "Extrinsics",
    "Image",
    "ImageObject",
    "Intrinsics",
    "Item",
    "KeyPoints",
    "KeyPoints3D",
    "PointCloud",
    "SchemaGroup",
    "SequenceFrame",
    "Track",
    "Tracklet",
    "Video",
    "View",
    "ViewEmbedding",
    "create_bbox",
    "create_bbox3d",
    "create_cam_calibration",
    "create_compressed_rle",
    "create_image",
    "create_image_object",
    "create_keypoints",
    "create_keypoints3d",
    "create_point_cloud",
    "create_sequence_frame",
    "create_track",
    "create_tracklet",
    "create_video",
    "create_view_embedding_function",
    "is_annotation",
    "is_base_schema",
    "is_bbox",
    "is_bbox3d",
    "is_cam_calibration",
    "is_compressed_rle",
    "is_embedding",
    "is_entity",
    "is_image",
    "is_item",
    "is_keypoints",
    "is_keypoints3d",
    "is_point_cloud",
    "is_sequence_frame",
    "is_track",
    "is_tracklet",
    "is_view",
    "is_video",
    "is_view_embedding",
    "register_schema",
]
