name: Build test and push latest Docker image

on:
  push:

env:
  TEST_TAG: pixano/pixano:test
  LATEST_TAG: pixano/pixano:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push test
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          mkdir -p library
          docker run -p 8000:8000 --name pixano -d ${{ env.TEST_TAG }}
          sleep 5
          curl http://localhost:8000
          docker stop pixano
          docker rm pixano


      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
