# =====================================
# Copyright: CEA-LIST/DIASI/SIALV/LVA
# Author : pixano@cea.fr
# License: CECILL-C
# =====================================

name: Lint and format backend

on:
  push:
    paths:
      - "pixano/**"
      - "tests/**"
    branches:
      - "develop"
      - "main"
  pull_request:
    paths:
      - "pixano/**"
      - "tests/**"
    branches:
      - "develop"


permissions:
  contents: read

jobs:
  lint_back:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install PyTorch and TensorFlow CPU versions manually to prevent installing CUDA
      # Install SAM and MobileSAM manually as they cannot be included in PyPI
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install torch~=2.2.0 torchaudio~=2.2.0 torchvision~=0.17.0 --index-url https://download.pytorch.org/whl/cpu
          python -m pip install tensorflow-cpu~=2.15.0
          python -m pip install ruff ~= 0.3.9

      - name: Lint backend code with Ruff
        run: |
          ruff check --fix
  format_back:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Format backend code with ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.3.9
          args: format
