name: Version

on:
  pull_request:
    paths:
      - "VERSION"
    branches:
      - "main"

permissions:
  contents: write

jobs:
  # Update backend and frontend versions triggered by VERSION file
  update_version:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: |
          VERSION=$(cat VERSION)
          echo "# =====================================" > src/pixano/__version__.py
          echo "# Copyright: CEA-LIST/DIASI/SIALV/LVA" >> src/pixano/__version__.py
          echo "# Author : pixano@cea.fr" >> src/pixano/__version__.py
          echo "# License: CECILL-C" >> src/pixano/__version__.py
          echo "# =====================================" >> src/pixano/__version__.py
          echo "" >> src/pixano/__version__.py
          echo "__version__ = \"${VERSION}\"" >> src/pixano/__version__.py
          sed -i 's/"version": "[^"]*"/"version": "'${VERSION}'"/' ui/apps/pixano/package.json
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git diff --cached --quiet && echo "Version already up to date" && exit 0
          git commit -m "Update version to ${VERSION}"
          git push origin HEAD:${{ github.head_ref }}
